# local dev env only!!!

version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - PORT=3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
volumes:
  pgdata:
